### ISSUE TITLE
Feature Request- Option to add 2 or more local file intros

### ISSUE THREAD

**Issue by rocksolid2018** [dkanada/jellyfin-plugin-intros#28]
JellyFin version 10.6.4
plugin version 1.3.0.0

Local file option for intros works great, request to add option to play multiple(at least 2) local intros videos

**Comment by feelingwalnut** [comment]
it looks like it is supposed to pick from a folder at random but does not appear to be functional (or i can't figure it out) it was new feature released with the 1.3.0.0 update
"Add a file or directory to use files instead of remote videos. Items in a directory will be randomized."

everything else works great.

**Comment by rocksolid2018** [comment]
It doesn't randomise files in a directory. I have setup a script to auto download trailers on to the folder. But I can only map one file to play at a time.

**Comment by dkanada** [comment]
It's supposed to randomize the files, there's just an issue with the feature right now.

**Comment by feelingwalnut** [comment]
looks like weedalf forked and added this feature as well but i'm not set up to compile dotnet stuff so i can't test it.
https://github.com/dkanada/jellyfin-plugin-intros/compare/master...Weedalf:master

**Comment by JonathanTreffler** [comment]
> It's supposed to randomize the files, there's just an issue with the feature right now.

Can you give an ETA for a fix ?
